// <auto-generated />
namespace DiscussionForum.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changePictureImageData2string : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changePictureImageData2string));
        
        string IMigrationMetadata.Id
        {
            get { return "201908261834091_changePicture.ImageData2string"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
