// <auto-generated />
namespace DiscussionForum.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addDiscussion_2_AnimeModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addDiscussion_2_AnimeModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201909041639511_addDiscussion_2_AnimeModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
