// <auto-generated />
namespace DiscussionForum.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatedLastUpdated_w_NewProperties : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedLastUpdated_w_NewProperties));
        
        string IMigrationMetadata.Id
        {
            get { return "201907061937423_updatedLastUpdated_w_NewProperties"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
