// <auto-generated />
namespace DiscussionForum.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changeLocalPopularity_2_FeedPriorityIFeedItem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeLocalPopularity_2_FeedPriorityIFeedItem));
        
        string IMigrationMetadata.Id
        {
            get { return "201909041742363_changeLocalPopularity_2_FeedPriorityIFeedItem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
