// <auto-generated />
namespace DiscussionForum.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateNewAnimeReport_w_AnilitIdsArray : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateNewAnimeReport_w_AnilitIdsArray));
        
        string IMigrationMetadata.Id
        {
            get { return "201907130435026_updateNewAnimeReport_w_AnilitIdsArray"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
