// <auto-generated />
namespace DiscussionForum.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateUser_w_Bio : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateUser_w_Bio));
        
        string IMigrationMetadata.Id
        {
            get { return "201910300209243_updateUser_w_Bio"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
