// <auto-generated />
namespace DiscussionForum.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateAnimeModel_w_ImageUrl_Sizes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateAnimeModel_w_ImageUrl_Sizes));
        
        string IMigrationMetadata.Id
        {
            get { return "201907062238293_updateAnimeModel_w_ImageUrl_Sizes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
