// <auto-generated />
namespace DiscussionForum.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateComment_w_CommentorPic : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateComment_w_CommentorPic));
        
        string IMigrationMetadata.Id
        {
            get { return "201911012144274_updateComment_w_CommentorPic"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
