// <auto-generated />
namespace DiscussionForum.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addLocalPopularity_2_IFeedItem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addLocalPopularity_2_IFeedItem));
        
        string IMigrationMetadata.Id
        {
            get { return "201909041546422_addLocalPopularity_2_IFeedItem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
