// <auto-generated />
namespace DiscussionForum.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatePicture_removeImageUrl_addImageData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatePicture_removeImageUrl_addImageData));
        
        string IMigrationMetadata.Id
        {
            get { return "201908182044154_updatePicture_removeImageUrl_addImageData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
