// <auto-generated />
namespace DiscussionForum.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addBridge4AnimeModel_NewAnimeReport : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addBridge4AnimeModel_NewAnimeReport));
        
        string IMigrationMetadata.Id
        {
            get { return "201907130445077_addBridge4AnimeModel_NewAnimeReport"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
