// <auto-generated />
namespace DiscussionForum.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateAnimeModel_w_LastUpdatesisNullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateAnimeModel_w_LastUpdatesisNullable));
        
        string IMigrationMetadata.Id
        {
            get { return "201907080200061_updateAnimeModel_w_LastUpdatesisNullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
