// <auto-generated />
namespace DiscussionForum.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addM2M_tags_Discussions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addM2M_tags_Discussions));
        
        string IMigrationMetadata.Id
        {
            get { return "201907281750404_addM2M_tags_Discussions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
