// <auto-generated />
namespace DiscussionForum.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UpdateDiscussion_w_IsAttachedToNewsIsAttachedToAnime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpdateDiscussion_w_IsAttachedToNewsIsAttachedToAnime));
        
        string IMigrationMetadata.Id
        {
            get { return "201910061613530_UpdateDiscussion_w_IsAttachedToNews-IsAttachedToAnime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
